[cerebrium.deployment]
name = "demucs-serve"

[cerebrium.hardware]
cpu = 4
memory = 16.0
compute = "ADA_L4"
gpu_count = 1

[cerebrium.scaling]
min_replicas = 0
max_replicas = 10
replica_concurrency = 1
cooldown = 60

[cerebrium.runtime.custom]
port = 8185
healthcheck_endpoint = "/health"
readycheck_endpoint = "/ready"
dockerfile_path = "./Dockerfile"
