[cerebrium.deployment]
name = "demucs-serve"
python_version = "3.11"
include = ['./*', 'main.py', 'cerebrium.toml', 'Dockerfile']
exclude = ['.*']

[cerebrium.hardware]
cpu = 4
memory = 16.0
compute = "ADA_L4"
gpu_count = 1
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
replica_concurrency = 1
cooldown = 60

[cerebrium.runtime.custom]
port = 8185
healthcheck_endpoint = "/health"
readycheck_endpoint = "/ready"
dockerfile_path = "./Dockerfile"
